version: "3.3"
services:
    main-app:
        build:
            context: .
            dockerfile: build/production.Dockerfile
        #image: ${DOCKER_REGISTRY}/main-app:${VERSION}
        ports:
            - "80:80"
        
    postgresqldb:
        image: postgres:12
        environment:
            - POSTGRES_PASSWORD=Y78N86BWnQv5
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432


    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
        ports:
            - 8090:80